import type { ChapterDef } from "../types";

// §2.1 (Squares) and §2.2 (Higher Exponents) are playable. The outro closes stage 2; rewrite it
// as the chapter outro when §2.3–2.4 and the boss land.
const chapter: ChapterDef = {
  number: 2,
  codename: "THE STACK",
  aopsTitle: "Exponents",

  intro: [
    { who: "SYSTEM", text: "DESCENDING · SECTOR 2 · THE STACK · REACTOR STATE: COLD" },
    { who: "MOTH", text: "It's a tower. A big crystal tower, going down. Every level is glowing a little brighter than the one above it." },
    { who: "CUSTODIAN", text: "The Stack is my reactor. Each stage takes the output of the stage before and multiplies it by itself. That is how so little fuel made so much light." },
    { who: "CUSTODIAN", text: "It is also how a reactor runs away. A value multiplied by itself grows faster than you expect, Operator. Faster than I can afford to guess at." },
    { who: "YOU", text: "So we count the multiplications." },
    { who: "CUSTODIAN", text: "Yes. My builders had a notation for it. $2 \\cdot 2 \\cdot 2 \\cdot 2 \\cdot 2 \\cdot 2$ is $2^6$: the **base** $2$, multiplied, as many times as the **exponent** $6$ says." },
    { who: "MOTH", text: "$2^6$. That's like… twelve?" },
    { who: "CUSTODIAN", text: "It is sixty-four. This is why we begin with squares." },
  ],

  outro: [
    { who: "SYSTEM", text: "STACK · STAGES 1–2 STABLE · CASCADE LAWS VERIFIED · STAGES 3–4 DARK" },
    { who: "CUSTODIAN", text: "Two stages hold. Every law we used was proven by counting copies. I did not have to trust a single one." },
    { who: "CUSTODIAN", text: "One more thing I noticed. Every square is zero or more, and every even power too. No move I own can make one fall below zero." },
    { who: "MOTH", text: "Is that a rule?" },
    { who: "CUSTODIAN", text: "No. It is something that stays true **whatever** rule you use. I do not have a module for that kind of knowledge. I find I would like one." },
    { who: "CUSTODIAN", text: "The lower stages idle at an exponent of zero, and below that, the exponents go negative. I do not yet know what either means." },
    { who: "SYSTEM", text: "SECTOR 2 · STAGES 3–4 · AWAITING CHAPTER DATA" },
  ],

  skills: [
    { id: "sq.def", title: "Definition of Square", kind: "axiom", tactics: ["square_def", "square_def_rev"], lore: "a² = a · a. A number times itself. The coolant loop does nothing else." },
    {
      id: "sq.table",
      title: "Square Table",
      kind: "tool",
      tactics: ["square_table"],
      lore: "The squares of 0 through 29, remembered. You wrote them out by hand often enough that the Custodian stopped asking you to.",
      compile: { uses: { "sq.def": 6 }, missions: ["2.1a"] },
    },
    { id: "sq.neg", title: "Square of Negation", kind: "axiom", tactics: ["square_neg"], lore: "(−a)² = a². The loop cannot tell a value from its mirror." },
    { id: "sq.mul", title: "Square of Product", kind: "axiom", tactics: ["square_product", "square_product_rev"], lore: "(ab)² = a²b². Squaring passes through a product, in either direction." },
    { id: "sq.recip", title: "Square of Reciprocal", kind: "axiom", tactics: ["square_recip", "square_recip_rev"], lore: "(1/a)² = 1/a². The answer that undoes, squared, undoes a square." },
    { id: "sq.div", title: "Square of Quotient", kind: "axiom", tactics: ["square_quotient", "square_quotient_rev"], lore: "(a ÷ b)² = a² ÷ b². Proven from the product and reciprocal laws before it was trusted." },
    {
      id: "sq.next",
      title: "Next Square",
      kind: "theorem",
      tactics: ["square_next"],
      lore: "(a + 1)² = a² + 2a + 1. Not an axiom: you proved it, so the Custodian runs it. The first rule in the table that neither it nor the builders wrote.",
      compile: { missions: ["2.1d"] },
    },
    {
      id: "pow.def",
      title: "Definition of Power",
      kind: "axiom",
      tactics: ["pow_def", "pow_def_rev", "pow_one", "pow_one_rev"],
      supersedes: ["sq.def"],
      lore: "aⁿ is n copies of a, multiplied. a¹ is a. The square was only the first stage.",
    },
    {
      id: "pow.table",
      title: "Power Table",
      kind: "tool",
      tactics: ["pow_table", "pow_table_rev"],
      supersedes: ["sq.table"],
      lore: "Any whole-number power up to a million, looked up in one step, and any perfect power written back as a power of its smallest base. Compiled from all the copies you wrote out.",
      compile: { uses: { "pow.def": 5 }, missions: ["2.2a"] },
    },
    { id: "pow.neg", title: "Power of Negation", kind: "axiom", tactics: ["pow_neg"], supersedes: ["sq.neg"], lore: "(−a)ⁿ is aⁿ for even n and −aⁿ for odd n. Mirrors cancel in pairs; an odd one is left over." },
    {
      id: "pow.mul",
      title: "Powers of Products and Quotients",
      kind: "axiom",
      tactics: ["pow_product", "pow_product_rev", "pow_recip", "pow_recip_rev", "pow_quotient", "pow_quotient_rev"],
      supersedes: ["sq.mul", "sq.recip", "sq.div"],
      lore: "(ab)ⁿ = aⁿbⁿ, (1/b)ⁿ = 1/bⁿ, (a ÷ b)ⁿ = aⁿ ÷ bⁿ. The square laws, for every stage.",
    },
    {
      id: "pow.base",
      title: "Same-Base Laws",
      kind: "axiom",
      tactics: ["pow_add", "pow_add_rev", "pow_sub", "pow_pow", "pow_pow_rev"],
      lore: "aᵐaⁿ = aᵐ⁺ⁿ, aᵐ ÷ aⁿ = aᵐ⁻ⁿ, (aᵐ)ⁿ = aᵐⁿ. Count the copies and the exponents do the work.",
    },
  ],

  missions: [
    {
      id: "2.1a",
      section: "2.1 Squares",
      title: "COOLANT LOOP",
      grants: ["sq.def"],
      briefing: [
        { who: "CUSTODIAN", text: "The coolant loop squares whatever enters it. The square of $a$ is $a$ times itself: $a^2 = a \\cdot a$." },
        { who: "CUSTODIAN", text: "I do not compute a square. I rewrite it as a product, and your arithmetic unit does the rest." },
        { who: "CUSTODIAN", text: "Order matters. Powers are computed after brackets, and before multiplication and division. In $7 \\cdot 3^2$ the $3$ is squared first. My brackets already show this." },
        { who: "SYSTEM", text: "MODULE LOADED · sq.def" },
        { who: "MOTH", text: "It's called a square because 5 rows of 5 tiles is a square of 25 tiles. I looked it up. I'm helping." },
      ],
      problems: [
        { id: "2.1a-1", start: "3^2", goal: { type: "value" }, par: 2, flavor: "Prime the loop: one square." },
        { id: "2.1a-2", start: "7 * 3^2", goal: { type: "value" }, par: 3, flavor: "Square first, then multiply." },
        { id: "2.1a-3", start: "180 - 5 * 2^2", goal: { type: "value" }, par: 4, flavor: "Loop pressure: square, multiply, then subtract." },
        { id: "2.1a-4", start: "a * a + b * b", goal: { type: "match", expr: "a^2 + b^2" }, par: 2, flavor: "The loop's own log, written the long way. Collect each product into a square." },
        { id: "2.1a-5", start: "(2 * 3 + 5)^2", goal: { type: "value" }, par: 4, flavor: "The intake reads $(2x + 5)^2$, and the sensor reports $x = 3$. The value is already substituted: evaluate it.", hint: "Work inside the brackets first: $2 \\cdot 3$, then $+ 5$. Square last." },
        { id: "2.1a-6", start: "8 + 6 * (3 - 8)^2", goal: { type: "value" }, par: 5, flavor: "A difference inside the square. It comes out negative. Square it anyway." },
      ],
      debrief: [
        { who: "SYSTEM", text: "COOLANT LOOP CIRCULATING · STACK TEMPERATURE FALLING" },
        { who: "CUSTODIAN", text: "You have written squares as products many times now. I can hold a table of the small ones, $0^2$ through $29^2$, and skip the product." },
        { who: "SYSTEM", text: "NEW MODULE COMPILABLE · sq.table · OPEN THE INSTRUCTION SET TO COMPILE" },
      ],
    },
    {
      id: "2.1b",
      section: "2.1 Squares",
      title: "MIRROR IN THE LOOP",
      grants: ["sq.neg"],
      briefing: [
        { who: "CUSTODIAN", text: "A mirrored value has entered the loop. Before I load a module for it, you will prove it is safe." },
        { who: "CUSTODIAN", text: "The claim: $(-a)^2 = a^2$. The square of a mirror is the square of the original. You already hold everything needed to show it." },
        { who: "SYSTEM", text: "MODULE STAGED · sq.neg · QUARANTINED UNTIL PROVEN" },
      ],
      problems: [
        {
          id: "2.1b-1",
          start: "(-a)^2",
          goal: { type: "match", expr: "a^2" },
          par: 3,
          forbid: ["sq.neg"],
          flavor: "Prove the claim. The module you are proving is quarantined, so you cannot use it to prove itself.",
          hint: "Write the square as a product. Two mirrors make a window. Then collect the product back into a square.",
        },
        { id: "2.1b-2", start: "(-12)^2", goal: { type: "value" }, par: 2, flavor: "Quarantine lifted. $-12$ is past the table's reach, but $12$ is not." },
        {
          id: "2.1b-3",
          start: "(-5)^2 + -5^2",
          goal: { type: "value" },
          par: 3,
          flavor: "Two registers that look alike. Read the brackets: one is the square of a mirror, the other the mirror of a square.",
          hint: "$(-5)^2 = 5^2$. The other term is $-(5^2)$. A value and its mirror cancel.",
        },
        {
          id: "2.1b-4",
          start: "2 * (-2)^2 + 3 * (-2) + 4",
          goal: { type: "value" },
          par: 6,
          flavor: "The loop reads $2x^2 + 3x + 4$ at $x = -2$. Every $x$ became $(-2)$, brackets included.",
          // Five operations, and squaring a negation takes two moves; too wide for the search
          // budget, so authored.
          solution: [
            { path: [0, 0, 1], tactic: "square_neg" },
            { path: [0, 0, 1], tactic: "square_table" },
            { path: [0, 0], tactic: "alu_arithmetic" },
            { path: [0, 1], tactic: "alu_arithmetic" },
            { path: [0], tactic: "alu_arithmetic" },
            { path: [], tactic: "alu_arithmetic" },
          ],
        },
        { id: "2.1b-5", start: "(-4)^2 * (-4 - 2)", goal: { type: "value" }, par: 4, flavor: "$x^2(x - t)$, with $x = -4$ and $t = 2$." },
      ],
      debrief: [
        { who: "SYSTEM", text: "MIRROR FLOW STABLE · sq.neg VERIFIED" },
        { who: "CUSTODIAN", text: "A square of a mirror is positive. A square of a positive is positive. The square of zero is zero. So no square is ever below zero." },
        { who: "MOTH", text: "And $-5^2$?" },
        { who: "CUSTODIAN", text: "Is not a square. It is the mirror of one. Read the brackets, MOTH." },
      ],
    },
    {
      id: "2.1c",
      section: "2.1 Squares",
      title: "PHASE COUPLERS",
      grants: ["sq.mul", "sq.recip", "sq.div"],
      briefing: [
        { who: "CUSTODIAN", text: "The couplers square whole products at once. Squaring passes through a product: $(ab)^2 = a^2 b^2$. And through a reciprocal: $\\left(\\frac{1}{a}\\right)^2 = \\frac{1}{a^2}$." },
        { who: "CUSTODIAN", text: "A third law, for quotients, is staged. Division is multiplication by a reciprocal, so you can prove it from the other two." },
        { who: "SYSTEM", text: "MODULES LOADED · sq.mul · sq.recip · sq.div (QUARANTINED UNTIL PROVEN)" },
        { who: "MOTH", text: "Does it pass through sums too? $(5 + 6)^2 = 5^2 + 6^2$?" },
        { who: "CUSTODIAN", text: "No. Try it on a coupler and I will show you exactly why not." },
      ],
      problems: [
        {
          id: "2.1c-1",
          start: "(a * b)^2",
          goal: { type: "match", expr: "a^2 * b^2" },
          par: 4,
          forbid: ["sq.mul"],
          flavor: "First, earn the law. Prove $(ab)^2 = a^2 b^2$ without it.",
          hint: "Write the square as a product, rearrange the four factors into $(a \\cdot a)(b \\cdot b)$, then collect each pair.",
          solution: [
            { path: [], tactic: "square_def" },
            { path: [], tactic: "rearrange_product", params: { expr: "(a * a) * (b * b)" } },
            { path: [0], tactic: "square_def_rev" },
            { path: [1], tactic: "square_def_rev" },
          ],
        },
        { id: "2.1c-2", start: "(3 * x)^2", goal: { type: "match", expr: "9 * x^2" }, par: 2, flavor: "A coupler with a variable load." },
        {
          id: "2.1c-3",
          start: "4^2 * 25^2",
          goal: { type: "value" },
          par: 4,
          forbid: ["alu.3"],
          flavor: "The full multiplier is overheating: small loads only. $16 \\cdot 625$ is too much for it. Is there a product you would rather square?",
          hint: "Run the Square of Product law backwards: $4^2 \\cdot 25^2 = (4 \\cdot 25)^2$.",
        },
        { id: "2.1c-4", start: "recip(7)^2", goal: { type: "match", expr: "recip(49)" }, par: 2, flavor: "An inverse enters the loop." },
        {
          id: "2.1c-5",
          start: "(a / b)^2",
          goal: { type: "match", expr: "a^2 / b^2" },
          par: 4,
          forbid: ["sq.div"],
          flavor: "Prove the quotient law. Division is multiplication by a reciprocal, and you hold laws for both.",
          hint: "Definition of Division, Square of Product, Square of Reciprocal, then Definition of Division backwards.",
        },
        { id: "2.1c-6", start: "480^2 / 40^2", goal: { type: "value" }, par: 3, flavor: "Quarantine lifted. $480^2$ is a large number. Do you need it?" },
      ],
      debrief: [
        { who: "SYSTEM", text: "PHASE COUPLERS LOCKED · sq.div VERIFIED · STACK OUTPUT 12%" },
        { who: "CUSTODIAN", text: "Two of those laws you did not receive. You derived them, and I accepted them because I watched every step." },
        { who: "MOTH", text: "So I can't just **tell** you things." },
        { who: "CUSTODIAN", text: "You may tell me anything. I will only run what is proven." },
      ],
    },
    {
      id: "2.1d",
      section: "2.1 Squares",
      title: "NEXT SQUARE",
      briefing: [
        { who: "CUSTODIAN", text: "The Stack's stages are numbered, and each stage's load is the square of its number. To step from one stage to the next, I need $(a + 1)^2$ from $a^2$." },
        { who: "CUSTODIAN", text: "Squaring does not pass through sums. So what **is** the square of a sum? First, measure how wrong the easy answer is." },
        { who: "MOTH", text: "I would like it noted that I predicted squares pass through sums and was wrong in a very reasonable way." },
      ],
      problems: [
        {
          id: "2.1d-1",
          start: "(7 + 5)^2 - 7^2 - 5^2",
          goal: { type: "value" },
          par: 6,
          flavor: "If squares passed through sums, this register would read $0$. Read it.",
          // Six operations, one move each; too wide for the search budget, so authored.
          solution: [
            { path: [0, 0, 0], tactic: "alu_arithmetic" },
            { path: [0, 0], tactic: "square_table" },
            { path: [0, 1], tactic: "square_table" },
            { path: [0], tactic: "alu_arithmetic" },
            { path: [1], tactic: "square_table" },
            { path: [], tactic: "alu_arithmetic" },
          ],
        },
        {
          id: "2.1d-2",
          start: "(a + 1)^2",
          goal: { type: "match", expr: "a^2 + a + (a + 1)" },
          par: 7,
          flavor: "The proof, part one. Expand $(a + 1)^2$ with the Distributor, and keep every step honest.",
          hint: "Write the square as $(a + 1)(a + 1)$ and distribute, then distribute again. Collect $a \\cdot a$ into $a^2$. A factor of $1$ only drops when it is on the left, so commute first where needed.",
        },
        {
          id: "2.1d-3",
          start: "a^2 + a + (a + 1)",
          goal: { type: "match", expr: "a^2 + 2 * a + 1" },
          par: 5,
          flavor: "Part two. Gather the two lone $a$'s into $2a$.",
          hint: "Rearrange the sum so that $a + a$ sits together. Each $a$ is $1 \\cdot a$ (turn on “Introducing moves” in the drawer), and $1 \\cdot a + 1 \\cdot a$ factors.",
          solution: [
            { path: [], tactic: "rearrange_sum", params: { expr: "a^2 + (a + a) + 1" } },
            { path: [0, 1, 0], tactic: "mult_one_rev" },
            { path: [0, 1, 1], tactic: "mult_one_rev" },
            { path: [0, 1], tactic: "factor_right" },
            { path: [0, 1, 0], tactic: "alu_arithmetic" },
          ],
        },
      ],
      debrief: [
        { who: "CUSTODIAN", text: "$(7 + 5)^2 - 7^2 - 5^2 = 70$, which is $2 \\cdot 7 \\cdot 5$. The missing piece is twice the product. I see it now in $2a$." },
        { who: "CUSTODIAN", text: "You proved $(a + 1)^2 = a^2 + 2a + 1$ for every $a$, not only for the ones we tried. I can compile a proof, Operator. A proven statement is a rule." },
        { who: "SYSTEM", text: "NEW MODULE COMPILABLE · sq.next · CLASS: THEOREM" },
        { who: "MOTH", text: "So we just… wrote a new law of math. Into an alien computer." },
        { who: "CUSTODIAN", text: "Not a new law. An old one, found again. The builders would have known it. But this copy is yours." },
      ],
    },
    {
      id: "2.1e",
      section: "2.1 Squares",
      title: "STAGE LADDER",
      requires: ["sq.next"],
      briefing: [
        { who: "CUSTODIAN", text: "With the theorem compiled, I can climb the Stack one stage at a time: $(a + 1)^2 = a^2 + 2a + 1$. Split a number by place value to find the $+ 1$." },
        { who: "SYSTEM", text: "STACK LADDER · STAGES 101 AND 901 · FULL MULTIPLIER OFFLINE FOR THE CLIMB" },
      ],
      problems: [
        { id: "2.1e-1", start: "901^2", goal: { type: "match", expr: "900^2 + 2 * 900 + 1" }, par: 2, flavor: "A $901 \\times 901$ grid is a $900 \\times 900$ square, two strips of $900$, and one lonely corner tile. Show it." },
        {
          id: "2.1e-2",
          start: "101^2",
          goal: { type: "value" },
          par: 7,
          forbid: ["alu.3"],
          flavor: "Stage 101. The full multiplier is offline, and $101 \\cdot 101$ is too big for the smaller units. Climb from stage 100.",
          hint: "$101 = 100 + 1$. Then Next Square, and every product left is round.",
          solution: [
            { path: [0], tactic: "base10_decompose" },
            { path: [], tactic: "square_next", params: { choice: "0" } },
            { path: [0, 0], tactic: "square_def" },
            { path: [0, 0], tactic: "alu_one_round" },
            { path: [0, 1], tactic: "alu_one_round" },
            { path: [0], tactic: "alu_one_round" },
            { path: [], tactic: "alu_one_round" },
          ],
        },
      ],
      debrief: [
        { who: "SYSTEM", text: "STAGE LADDER CLIMBED · STACK STAGE 1 · OUTPUT 25%" },
        { who: "MOTH", text: "$10201$. And I didn't even guess! I mean, I did guess, but then you proved it, so it counts." },
        { who: "CUSTODIAN", text: "It counts." },
      ],
    },
    {
      id: "2.2a",
      section: "2.2 Higher Exponents",
      title: "CASCADE STAGES",
      grants: ["pow.def"],
      briefing: [
        { who: "CUSTODIAN", text: "The coolant loop was stage one. The cascade below it multiplies three copies, four, more. $7^3$ is **7 cubed**: $7 \\cdot 7 \\cdot 7$. $7^4$ is **7 to the 4th**." },
        { who: "CUSTODIAN", text: "The rule is the same for every stage: $a^n$ is $n$ copies of $a$, multiplied. And $a^1$ is one copy: just $a$." },
        { who: "SYSTEM", text: "MODULE LOADED · pow.def · SUPERSEDES sq.def" },
        { who: "MOTH", text: "So a square is a power with exponent 2, a cube is exponent 3, and after that they ran out of shapes." },
      ],
      problems: [
        { id: "2.2a-1", start: "7^3", goal: { type: "value" }, par: 3, flavor: "Stage 2 intake: $7$ cubed." },
        { id: "2.2a-2", start: "(-4)^3", goal: { type: "value" }, par: 3, flavor: "A mirror enters the cascade. Squares of mirrors were positive. Cubes?" },
        { id: "2.2a-3", start: "a * a * a * a * a", goal: { type: "match", expr: "a^5" }, par: 1, flavor: "The cascade log, written the long way. Collect it." },
        { id: "2.2a-4", start: "17^1 * a^1", goal: { type: "match", expr: "17 * a" }, par: 2, flavor: "Single-copy stages." },
        {
          id: "2.2a-5",
          start: "a^2 * a^3",
          goal: { type: "match", expr: "a^5" },
          par: 3,
          flavor: "Two copies of $a$, then three more. How many in all?",
          hint: "Write both powers out, then collect the whole product.",
        },
      ],
      debrief: [
        { who: "SYSTEM", text: "CASCADE STAGE 2 PRIMED" },
        { who: "CUSTODIAN", text: "$(-4)^3 = -64$. Unlike a square, a cube can be negative. Hold on to that." },
        { who: "CUSTODIAN", text: "You have written out enough copies. I can compile a table of powers, and read it backwards too: $64$ is $2^6$." },
        { who: "SYSTEM", text: "NEW MODULE COMPILABLE · pow.table · SUPERSEDES sq.table" },
      ],
    },
    {
      id: "2.2b",
      section: "2.2 Higher Exponents",
      title: "ORDER IN THE STACK",
      requires: ["pow.table"],
      briefing: [
        { who: "CUSTODIAN", text: "Addition and multiplication are commutative and associative. Before I wire the stages together, I must know whether exponentiation is." },
        { who: "CUSTODIAN", text: "One convention first. A tower of exponents, $2^{2^3}$, is read from the top down: $2^{(2^3)}$." },
      ],
      problems: [
        { id: "2.2b-1", start: "3^4 - 4^3", goal: { type: "value" }, par: 3, flavor: "Swap base and exponent. If powers commuted, this register would read $0$." },
        { id: "2.2b-2", start: "2^2^3 - (2^2)^3", goal: { type: "value" }, par: 5, flavor: "Move the brackets. If powers were associative, this would read $0$ too." },
        { id: "2.2b-3", start: "3^4 - 5 * 8", goal: { type: "value" }, par: 3, flavor: "Powers first, then products, then the difference." },
      ],
      debrief: [
        { who: "CUSTODIAN", text: "$3^4 = 81$ and $4^3 = 64$. $2^{(2^3)} = 256$ and $(2^2)^3 = 64$. Exponentiation is neither commutative nor associative. The order of the stages matters, and so do the brackets." },
        { who: "MOTH", text: "Finally, an operation as confused as I am." },
      ],
    },
    {
      id: "2.2c",
      section: "2.2 Higher Exponents",
      title: "SIGN CASCADE",
      grants: ["pow.neg"],
      briefing: [
        { who: "CUSTODIAN", text: "Mirrored values run through every stage. Two mirrors make a window, so mirrors cancel in pairs. With an even exponent, they all pair off. With an odd one, one mirror is left over." },
        { who: "CUSTODIAN", text: "The law: $(-a)^n = a^n$ when $n$ is even, and $-a^n$ when $n$ is odd. As before, prove it before I run it." },
        { who: "SYSTEM", text: "MODULE STAGED · pow.neg · QUARANTINED UNTIL PROVEN" },
      ],
      problems: [
        {
          id: "2.2c-1",
          start: "(-a)^4",
          goal: { type: "match", expr: "a^4" },
          par: 5,
          forbid: ["pow.neg"],
          flavor: "Prove the even case for $n = 4$. Pair the mirrors.",
          hint: "Write out the four copies. Regroup so two pairs sit together, turn each pair of mirrors into $a \\cdot a$, then collect.",
        },
        { id: "2.2c-2", start: "(-2)^5", goal: { type: "value" }, par: 2, flavor: "Quarantine lifted. Five mirrors: one is left over." },
        { id: "2.2c-3", start: "(-1)^(5^2) + 1^(2^5)", goal: { type: "value" }, par: 6, flavor: "Compute each exponent first. Is $5^2$ even or odd?" },
        { id: "2.2c-4", start: "-1^2008 + (-1)^2007", goal: { type: "value" }, par: 4, flavor: "Read the brackets. One is a power of a mirror, the other the mirror of a power." },
        { id: "2.2c-5", start: "(1 - (-1)^11)^2", goal: { type: "value" }, par: 4, flavor: "An odd stage inside a square." },
      ],
      debrief: [
        { who: "SYSTEM", text: "SIGN CASCADE BALANCED · pow.neg VERIFIED" },
        { who: "CUSTODIAN", text: "An even power of anything is zero or more. An odd power keeps the sign it was given." },
      ],
    },
    {
      id: "2.2d",
      section: "2.2 Higher Exponents",
      title: "COMPOUND STAGES",
      grants: ["pow.mul"],
      briefing: [
        { who: "CUSTODIAN", text: "The square laws hold at every stage: $(ab)^n = a^n b^n$, $\\left(\\frac{1}{b}\\right)^n = \\frac{1}{b^n}$, and $(a \\div b)^n = a^n \\div b^n$. The proofs are the ones you already wrote, with more copies." },
        { who: "CUSTODIAN", text: "And the same warning: a power does **not** pass through a sum. $(1 + 1)^3 = 8$, but $1^3 + 1^3 = 2$." },
        { who: "SYSTEM", text: "MODULE LOADED · pow.mul · SUPERSEDES sq.mul · sq.recip · sq.div" },
      ],
      problems: [
        { id: "2.2d-1", start: "(2 * x)^3", goal: { type: "match", expr: "8 * x^3" }, par: 2, flavor: "A coupled load, cubed." },
        { id: "2.2d-2", start: "(a * b * c)^4", goal: { type: "match", expr: "a^4 * b^4 * c^4" }, par: 2, flavor: "Three factors. The law works on two at a time." },
        { id: "2.2d-3", start: "recip(2)^5", goal: { type: "match", expr: "recip(32)" }, par: 2, flavor: "An inverse through five stages." },
        {
          id: "2.2d-4",
          start: "25^3 * 4^3",
          goal: { type: "value" },
          par: 3,
          forbid: ["alu.3"],
          flavor: "The full multiplier is overheating again. $15625 \\cdot 64$ is too heavy. Couple the bases first.",
        },
        { id: "2.2d-5", start: "88888^4 / 22222^4", goal: { type: "value" }, par: 3, flavor: "These powers are far beyond any table. Do you need them?" },
      ],
      debrief: [
        { who: "SYSTEM", text: "COMPOUND STAGES LOCKED · STACK OUTPUT 48%" },
        { who: "MOTH", text: "$88888^4 \\div 22222^4 = 256$. I would have tried to multiply $88888$ by itself. Four times. Out loud." },
      ],
    },
    {
      id: "2.2e",
      section: "2.2 Higher Exponents",
      title: "SAME-BASE COUPLING",
      grants: ["pow.base"],
      briefing: [
        { who: "CUSTODIAN", text: "Now the stages feed each other. When the bases match, only the count of copies matters." },
        { who: "CUSTODIAN", text: "$a^m \\cdot a^n = a^{m + n}$. $a^m \\div a^n = a^{m - n}$, for now only when $m$ is larger. And $(a^m)^n = a^{mn}$." },
        { who: "SYSTEM", text: "MODULE STAGED · pow.base · PRODUCT LAW QUARANTINED UNTIL PROVEN" },
      ],
      problems: [
        {
          id: "2.2e-1",
          start: "a^3 * a^5",
          goal: { type: "match", expr: "a^8" },
          par: 3,
          forbid: ["pow.base"],
          flavor: "Prove it by counting: three copies, then five.",
        },
        { id: "2.2e-2", start: "9^7 / 9^3", goal: { type: "match", expr: "9^4" }, par: 2, flavor: "Seven nines, three cancelled." },
        { id: "2.2e-3", start: "(2^7 * 2^8) / 2^3", goal: { type: "match", expr: "2^12" }, par: 4, flavor: "Express it as a single power of 2." },
        { id: "2.2e-4", start: "(2^6)^4 / 2^7", goal: { type: "match", expr: "2^17" }, par: 4, flavor: "A stage of stages, then a cut." },
        { id: "2.2e-5", start: "(2^3)^2 - (2^2)^3", goal: { type: "value" }, par: 4, flavor: "The square of the cube of 2, minus the cube of its square. You could compute both. Or not." },
        {
          id: "2.2e-6",
          start: "4^6 / 8^2",
          goal: { type: "match", expr: "2^6" },
          par: 4,
          flavor: "Different bases, but both are powers of 2. The book's route takes eight moves. The builders knew one with four.",
          hint: "The book's route: $4 = 2^2$ and $8 = 2^3$, then Power of Power on each side. The short one: what is $8^2$ as a power of 2? Then both powers have the same exponent.",
        },
      ],
      debrief: [
        { who: "SYSTEM", text: "SAME-BASE COUPLING ONLINE · STACK OUTPUT 71%" },
        { who: "CUSTODIAN", text: "Multiply the powers, add the exponents. Raise a power, multiply them. The arithmetic moves up a floor." },
      ],
    },
    {
      id: "2.2f",
      section: "2.2 Higher Exponents",
      title: "THREE GIANTS",
      briefing: [
        { who: "SYSTEM", text: "WARNING · THREE CANDIDATE FEEDS · $11^{20000}$ · $5^{30000}$ · $2^{70000}$ · SELECT THE STRONGEST" },
        { who: "CUSTODIAN", text: "I cannot compute any of these. No table can. But if all three were $10000$th powers, I would only have to compare their bases." },
        { who: "MOTH", text: "$2$ is the smallest base, so $2^{70000}$ is the smallest. Easy!" },
        { who: "CUSTODIAN", text: "Prove it." },
      ],
      problems: [
        {
          id: "2.2f-1",
          start: "11^20000",
          goal: { type: "match", expr: "121^10000" },
          par: 3,
          flavor: "Rewrite the first feed as a $10000$th power.",
          hint: "Factor the exponent: $20000 = 2 \\cdot 10000$. Then Power of Power, backwards.",
          solution: [
            { path: [1], tactic: "int_factor", params: { p: "2", q: "10000" } },
            { path: [], tactic: "pow_pow_rev" },
            { path: [0], tactic: "pow_table" },
          ],
        },
        {
          id: "2.2f-2",
          start: "5^30000",
          goal: { type: "match", expr: "125^10000" },
          par: 3,
          flavor: "The second feed.",
          solution: [
            { path: [1], tactic: "int_factor", params: { p: "3", q: "10000" } },
            { path: [], tactic: "pow_pow_rev" },
            { path: [0], tactic: "pow_table" },
          ],
        },
        {
          id: "2.2f-3",
          start: "2^70000",
          goal: { type: "match", expr: "128^10000" },
          par: 3,
          flavor: "The third feed.",
          solution: [
            { path: [1], tactic: "int_factor", params: { p: "7", q: "10000" } },
            { path: [], tactic: "pow_pow_rev" },
            { path: [0], tactic: "pow_table" },
          ],
        },
      ],
      debrief: [
        { who: "CUSTODIAN", text: "$121^{10000}$, $125^{10000}$, $128^{10000}$. Same exponent, so the largest base wins: $2^{70000}$ is the strongest feed." },
        { who: "MOTH", text: "The smallest base won. I would like to formally withdraw “Easy!”." },
        { who: "SYSTEM", text: "FEED SELECTED · STACK STAGE 2 ONLINE · OUTPUT 88%" },
      ],
    },
  ],
};

export default chapter;
