import { defineRules } from "../engine/defineRule";
import { CH1 } from "./_chapters";

const section = "Division";

const NO_DIVIDING_INTO_SUM =
  "Dividing **into** a number does not distribute over addition or subtraction: $a \\div (b + c)$ does not have to equal $a \\div b + a \\div c$. Only a sum or difference being divided, as in $(a + b) \\div c$, can be split.";

export default defineRules([
  {
    id: "div_def",
    name: "Definition of Division",
    chapter: CH1,
    section,
    description: "For nonzero b: a ÷ b = a · (1/b).",
    lhs: "a / b",
    rhs: "a * recip(b)",
    nonzero: ["b"],
    bidirectional: true,
    everywhere: true,
  },
  {
    id: "div_into_zero",
    name: "Dividing into Zero",
    chapter: CH1,
    section,
    description: "For nonzero x: 0 ÷ x = 0.",
    lhs: "0 / x",
    rhs: "0",
    nonzero: ["x"],
  },
  {
    id: "div_self",
    name: "Self Division",
    chapter: CH1,
    section,
    description: "For nonzero x: x ÷ x = 1.",
    lhs: "x / x",
    rhs: "1",
    nonzero: ["x"],
  },
  {
    id: "div_by_one",
    name: "Dividing by 1",
    chapter: CH1,
    section,
    description: "x ÷ 1 = x.",
    lhs: "x / 1",
    rhs: "x",
    bidirectional: true,
    reverseName: "Dividing by 1 (introduce ÷ 1)",
  },
  {
    id: "div_into_one",
    name: "Dividing into 1",
    chapter: CH1,
    section,
    description: "For nonzero x: 1 ÷ x = 1/x.",
    lhs: "1 / x",
    rhs: "recip(x)",
    nonzero: ["x"],
    bidirectional: true,
  },
  {
    id: "div_by_recip",
    name: "Dividing by Reciprocal",
    chapter: CH1,
    section,
    description: "For nonzero y: x ÷ (1/y) = xy.",
    lhs: "x / recip(y)",
    rhs: "x * y",
    nonzero: ["y"],
    bidirectional: true,
  },
  {
    id: "div_into_neg",
    name: "Division into Negation",
    chapter: CH1,
    section,
    description: "For nonzero y: (−x) ÷ y = −(x ÷ y).",
    lhs: "(-x) / y",
    rhs: "-(x / y)",
    nonzero: ["y"],
    bidirectional: true,
  },
  {
    id: "div_by_neg",
    name: "Division by Negation",
    chapter: CH1,
    section,
    description: "For nonzero y: x ÷ (−y) = −(x ÷ y).",
    lhs: "x / (-y)",
    rhs: "-(x / y)",
    nonzero: ["y"],
    bidirectional: true,
  },
  {
    id: "div_neg_neg",
    name: "Negation Divided by Negation",
    chapter: CH1,
    section,
    description: "For nonzero y: (−x) ÷ (−y) = x ÷ y.",
    lhs: "(-x) / (-y)",
    rhs: "x / y",
    nonzero: ["y"],
    bidirectional: true,
  },
  {
    id: "div_cancel",
    name: "Cancel Common Factor",
    chapter: CH1,
    section,
    description: "For nonzero a and c: (ab) ÷ (ac) = b ÷ c.",
    lhs: "(a * b) / (a * c)",
    rhs: "b / c",
    nonzero: ["a", "c"],
  },
  {
    id: "div_dist_add",
    name: "Dividing a Sum",
    chapter: CH1,
    section,
    description: "For nonzero c: (a + b) ÷ c = a ÷ c + b ÷ c.",
    lhs: "(a + b) / c",
    rhs: "a / c + b / c",
    nonzero: ["c"],
    bidirectional: true,
    pitfalls: [{ when: "a / (b + c)", message: NO_DIVIDING_INTO_SUM }],
  },
  {
    id: "div_dist_sub",
    name: "Dividing a Difference",
    chapter: CH1,
    section,
    description: "For nonzero c: (a − b) ÷ c = a ÷ c − b ÷ c.",
    lhs: "(a - b) / c",
    rhs: "a / c - b / c",
    nonzero: ["c"],
    bidirectional: true,
    pitfalls: [{ when: "a / (b - c)", message: NO_DIVIDING_INTO_SUM }],
  },
  {
    id: "div_eq_relation",
    name: "Multiplication–Division Relation",
    chapter: CH1,
    section,
    description: "For nonzero a and b: if ab = c, then a = c ÷ b and b = c ÷ a.",
    lhs: "a * b = c",
    variants: [
      { label: "Solve for the first factor", rhs: "a = c / b" },
      { label: "Solve for the second factor", rhs: "b = c / a" },
    ],
    nonzero: ["a", "b"],
  },
]);
