import { defineRules } from "../engine/defineRule";
import { CH1 } from "./_chapters";

const section = "Subtraction";

export default defineRules([
  {
    id: "sub_def",
    name: "Definition of Subtraction",
    chapter: CH1,
    section,
    description: "Subtracting a number means adding its opposite: a − b = a + (−b).",
    lhs: "a - b",
    rhs: "a + (-b)",
    bidirectional: true,
    everywhere: true,
  },
  {
    id: "sub_from_zero",
    name: "Subtracting from Zero",
    chapter: CH1,
    section,
    description: "0 − x = −x.",
    lhs: "0 - x",
    rhs: "-x",
    bidirectional: true,
  },
  {
    id: "sub_self",
    name: "Self Subtraction",
    chapter: CH1,
    section,
    description: "x − x = 0.",
    lhs: "x - x",
    rhs: "0",
  },
  {
    id: "sub_zero",
    name: "Subtracting Zero",
    chapter: CH1,
    section,
    description: "x − 0 = x.",
    lhs: "x - 0",
    rhs: "x",
    bidirectional: true,
    reverseName: "Subtracting Zero (introduce − 0)",
  },
  {
    id: "sub_of_neg",
    name: "Subtraction of Negation",
    chapter: CH1,
    section,
    description: "x − (−y) = x + y.",
    lhs: "x - (-y)",
    rhs: "x + y",
    bidirectional: true,
  },
  {
    id: "sub_from_neg",
    name: "Subtraction from Negation",
    chapter: CH1,
    section,
    description: "−x − y = −(x + y).",
    lhs: "-x - y",
    rhs: "-(x + y)",
    bidirectional: true,
  },
  {
    id: "neg_of_sub",
    name: "Negation of Subtraction",
    chapter: CH1,
    section,
    description: "−(x − y) = −x + y = y − x.",
    lhs: "-(x - y)",
    variants: [
      { label: "−x + y", rhs: "-x + y" },
      { label: "y − x", rhs: "y - x" },
    ],
  },
  {
    id: "neg_of_sub_rev_sum",
    name: "Negation of Subtraction (reverse, from −x + y)",
    chapter: CH1,
    section,
    description: "−x + y = −(x − y).",
    lhs: "-x + y",
    rhs: "-(x - y)",
  },
  {
    id: "neg_of_sub_rev_diff",
    name: "Negation of Subtraction (reverse, from y − x)",
    chapter: CH1,
    section,
    description: "y − x = −(x − y).",
    lhs: "y - x",
    rhs: "-(x - y)",
  },
  {
    id: "sub_eq_relation",
    name: "Addition–Subtraction Relation",
    chapter: CH1,
    section,
    description: "If a + b = c, then a = c − b and b = c − a.",
    lhs: "a + b = c",
    variants: [
      { label: "Solve for the first addend", rhs: "a = c - b" },
      { label: "Solve for the second addend", rhs: "b = c - a" },
    ],
  },
]);
